mods.astralsorcery.Altar.addTraitAltarRecipe("tc_pearl",<thaumcraft:primordial_pearl>,5000,100,[
    null,<botania:rune>,null,
    <botania:rune:1>,<botania:manaresource:1>,<botania:rune:3>,
    null,<botania:rune:2>,null,
    <botania:rune:4>,<botania:rune:5>,<botania:rune:6>,<botania:rune:7>,
    null,null,null,null,null,null,null,null,
    null,null,null,null,
    <thaumcraft:void_seed>,<thaumcraft:void_seed>,<thaumcraft:void_seed>,<thaumcraft:void_seed>
],
"astralsorcery.constellation.pelotrio");